name: CI/CD

on:
  push:
    paths-ignore:
      - ".github/dependabot.yml"
      - "*.md"
      - "LICENSE"
      - "ncurc.json"
  pull_request:
    paths-ignore:
      - ".github/dependabot.yml"
      - "*.md"
      - "LICENSE"
      - "ncurc.json"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Bundle
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vsix
          path: sqltools-clickhouse-driver-*.vsix

  release:
    name: Release
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Create release body file
        run: |
          awk -v ver=$(grep 'version' package.json | awk -F: '{ print $2 }' | tr -d \ \",) '/^#+ \[/ { if (p) { exit }; if ($2 == "["ver"]") { p=1; next } } p && NF' CHANGELOG.md > changes.txt

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: vsix

      - name: Publish to Visual Studio Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npm run publish:vsce sqltools-clickhouse-driver-*.vsix

      - name: Publish to Open VSX Registry
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: npm run publish:ovsx vscode-choosealicense-*.vsix

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changes.txt
          files: |
            sqltools-clickhouse-driver-*.vsix
